### ISSUE TITLE
DODO Pool DVM contract  on the BSC return wrong values for querySell functions

### ISSUE THREAD

**Issue by francoispqt** [DODOEX/contractV2#10]
Hi,

I'm not sure I am opening the issue on the right repo. Please let me know if I should open it elsewhere.

Several DODO Pool DVM contract return wrong values for querySellBase or querySellQuote functions. Let me give you one example. 

I found the DODO Pool contract for the pair DAI/WBNB from the DVM Factory contract at the address [0x790B4A80Fb1094589A3c0eFC8740aA9b0C1733fB](https://bscscan.com/address/0x790B4A80Fb1094589A3c0eFC8740aA9b0C1733fB#readContract) by calling the getDODOPool function with DAI address [0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3](https://bscscan.com/address/0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3) as base token and WBNB address [0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c](https://bscscan.com/address/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c) as quote token, it returns the following DVM contract address [0x0aB58740A864d4ffFdefFa39C24Bf2845CdE9a09](https://bscscan.com/address/0x0aB58740A864d4ffFdefFa39C24Bf2845CdE9a09#readContract). 
On the pool DVM contract I run querySellBase with 1 GWEI and it returns 996999989, the querySellQuote returns the same value, this is obviously wrong and if I check on DODO app the exchange rate for DAI/WBNB should be around  0,003941 at time of writing.

<img width="455" alt="Screenshot 2021-03-16 at 21 59 53" src="https://user-images.githubusercontent.com/24575934/111379045-f5b47380-86a2-11eb-9bb7-f29c83901114.png">

Am I doing something wrong?

Edit:
After I checked the pair balance on these pools I see they're almost empty so I guess that explains why I get these rates. Am I correct ?

**Comment by owen05** [comment]
Yes, you are correct. 
People can create same trading pairs on DODO platform. And the registry on factory is an array type. Different trading pairs may have different feeRate, K, I, and also the ratio of two tokens.
You find the pool of DAI/WBNB is our testing pool having a big deviation from the market price. And also the liquidity is too small. The price will vary greatly.  
But no worry. Our front-end will choose the pool with best price. And also If you directly interact with our smart contract. Can also choose the pool with best price. But now DAI/WBNB on DODO have no liquidity yet.

**Comment by owen05** [comment]
closed
